const componentMapping = {
  'product-listing': 'plp',
  'product-description': 'pdp',
  header: 'header',
  footer: 'footer',
  'cart-review': 'cart_review',
  'cart-landing': 'cart_landing',
  'order-review': 'order_review',
  categories: 'categories',
  collections: 'collections',
  'screen-saver': 'screensaver',
  'compare-products': 'compare_products'
};

const getComponentKey = val => {
  return componentMapping[val];
};

const ALL_AVAILABLE_PAGES = [
  {
    path: "product",
    type: "system",
    sections: [],
    sections_meta: [],
    text: "Product Description",
    value: "product-description",
    props: [
      {
        type: "checkbox",
        id: "share",
        label: "Share",
        default: true,
        info: "Enable Sharing product",
      },
      {
        type: "checkbox",
        id: "wishlist",
        label: "Wishlist",
        default: true,
        info: "Show Wishlist for product",
      },
      {
        type: "checkbox",
        id: "bulk_prices",
        label: "Bulk Prices",
        default: false,
        info: "Show Bulk Prices",
      },
      {
        type: "checkbox",
        id: "reviews",
        label: "Review",
        default: true,
        info: "Show Reviews of product",
      },
      {
        type: "checkbox",
        id: "add_to_compare",
        label: "Add to Compare",
        default: true,
        info: "Allow comparison of products",
      },
      {
        type: "checkbox",
        id: "size_guide",
        label: "Size Guide",
        default: true,
        info: "Show Size Guide",
      },
      {
        type: "checkbox",
        id: "product_request",
        label: "Product Request",
        default: true,
        info: "Show Product Request",
      },
      {
        type: "checkbox",
        id: "store_selection",
        label: "Seller Store Selection",
        default: true,
        info: "Allow to explicitly select stores",
      },
      {
        type: "checkbox",
        id: "compare_products",
        label: "Compare Products",
        default: true,
        info: "Show Most Compared Products",
      },
      {
        type: "checkbox",
        id: "similar_products",
        label: "Similar Products",
        default: true,
        info: "Show Similar Products",
      },
      {
        type: "checkbox",
        id: "assistance",
        label: "Assistance",
        default: true,
        info: "Show Assistance",
      },
    ],
  },
  {
    path: "",
    type: "system",
    sections_meta: [
      {
        attributes: {
          page: "home",
        },
      },
    ],
    sections: [],
    value: "home",
    text: "Home",
    props: [],
  },
  {
    path: "brands",
    type: "system",
    sections_meta: [],
    sections: [],
    value: "brands",
    text: "Brands",
    props: [],
  },
  {
    path: "cart/bag",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "cart-landing",
    text: "Cart Landing",
    props: [
      {
        type: "checkbox",
        id: "gst",
        label: "GST",
        default: true,
        info: "Allows GST Input",
      },
      {
        type: "checkbox",
        id: "share_cart",
        label: "Share Cart",
        default: true,
        info: "Allows Sharing of Cart",
      },
      {
        type: "checkbox",
        id: "staff_selection",
        label: "Staff Selection",
        default: true,
        info: "Show Staff Selection",
      },
      {
        type: "checkbox",
        id: "checkout_mode",
        label: "Self Checkout Mode",
        default: true,
        info: "Show Self Checkout Mode ",
      },
      {
        type: "checkbox",
        id: "continue_as_guest",
        label: "Guest Checkout",
        default: true,
        info: "Allows Guest checkout ",
      },
    ],
  },
  {
    path: "categories",
    type: "system",
    sections_meta: [],
    sections: [],
    value: "categories",
    text: "Categories",
    props: [],
  },
  {
    path: "collections",
    type: "system",
    sections_meta: [],
    sections: [],
    value: "collections",
    text: "Collections",
    props: [],
  },
  {
    path: "cart/delivery",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "cart-delivery",
    text: "Cart Delivery",
    props: [],
  },
  {
    path: "cart/order-review",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "cart-review",
    text: "Cart Review",
    props: [],
  },
  {
    path: "blog",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "blog",
    text: "Blog",
    props: [],
  },
  {
    path: "compare",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "compare-products",
    text: "Compare Products",
    props: [],
  },
  {
    path: "contact-us",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "contact-us",
    text: "Contact Us",
    props: [],
  },
  {
    path: "faq",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "faq",
    text: "FAQ",
    props: [],
  },
  {
    path: "products",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "product-listing",
    text: "Product Listing",
    props: [],
  },
  {
    path: "profile",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "profile",
    text: "Profile",
    props: [],
  },
  {
    path: "profile/address",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "profile-address",
    text: "Profile Address",
    props: [],
  },
  {
    path: "profile/details",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "profile-details",
    text: "Profile Details",
    props: [],
  },
  {
    path: "collection",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "collection-listing",
    text: "Collection Listing",
    props: [],
  },
  {
    path: "wishlist",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "wishlist",
    text: "Wishlist",
    props: [],
  },
  {
    path: "product/:slug/reviews",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "product-reviews",
    text: "Product Reviews",
    props: [],
  },
  {
    path: "product/:slug/add-review",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "add-product-review",
    text: "Add Product Review",
    props: [],
  },
  {
    path: "orders/shipment/:shipmentId",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "shipment-details",
    text: "Shipment Details",
    props: [],
  },
  {
    path: "about-us",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "about-us",
    text: "About Us",
    props: [],
  },
  {
    path: "cart/payment-info",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "cart-payment",
    text: "Cart Payment",
    props: [],
  },
  {
    path: "cart/order-status/",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "order-status",
    text: "Order Status",
    props: [],
  },
  {
    path: "locate-us",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "locate-us",
    text: "Locate Us",
    props: [],
  },
  {
    path: "order-tracking/:orderId",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "order-tracking-details",
    text: "Order Tracking Details",
    props: [],
  },
  {
    path: "order-tracking",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "order-tracking",
    text: "Order Tracking",
    props: [],
  },
  {
    path: "profile/orders",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "orders-list",
    text: "Orders List",
    props: [],
  },
  {
    path: "shared-cart",
    type: "system",
    sections: [],
    sections_meta: [],
    value: "shared-cart",
    text: "Shared Cart",
    props: [],
  },
];
module.exports = { getComponentKey, ALL_AVAILABLE_PAGES };
