name: Run Validation on TAG and Publish Package to npmjs(beta)
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
              node-version: '16.x'
              registry-url: 'https://registry.npmjs.org'
        - run: npm install
        - run: node ./scripts/unstableReleaseCheck.js

        
  run-test-cases:
    needs: release-check
    uses: ./.github/workflows/call_test_cases.yml
   
  
  publish-test-release:
    needs: 
      - release-check
      - run-test-cases
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install NPM package
        run: npm install
        
      - name: get version
        id: fdk-cli-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      - name: Build the project
        run: npm run build

      - name: Installing sentry
        run: npm i -g @sentry/cli@2.28.6

      - name: Add Debug Id to dist
        run: sentry-cli sourcemaps inject --org ${{ env.SENTRY_ORG }} --project ${{ env.SENTRY_PROJECT }} ./dist
        env:
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      - name: Upload source map to Sentry
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: development
          sourcemaps: './dist'
          version: ${{ steps.fdk-cli-version.outputs.current-version }}

      # # Alternative of above to try in local
      # - name: Upload source map to Sentry
      #   run: sentry-cli sourcemaps upload --org ${{ env.SENTRY_ORG }} --project ${{ env.SENTRY_PROJECT }} --release ${{ env.RELEASE_VERSION }} --auth-token ${{ env.SENTRY_AUTH_TOKEN }} ./dist
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      #     SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      #     SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      #     RELEASE_VERSION: ${{ steps.fdk-cli-version.outputs.current-version }}

      - name: Adding Sentry DSN
        run: | 
          echo "{\"dsn\": \"${{ secrets.SENTRY_DSN }}\"}" > ./dist/sentry.json
          
      - name: Delete SourceMap files
        run: find ./dist -type f -name '*.map' -exec rm -f {} \;

      - name: Publish to npmjs (beta)
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION }}