name: Run Validation on TAG and Publish Package to npmjs(beta)
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+

jobs:
  run-test-cases:
    uses: ./.github/workflows/call_test_cases.yml

  publish-test-release:
    needs: run-test-cases
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install NPM package
        run: npm install
      
      - name: Release Check
        run: node ./scripts/unstableReleaseCheck.js

      - name: Publish to npmjs (beta)
        run: npm publish --tag beta --access public
        if: contains(github.ref, '-beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION }}